---
- name: Install, configure and run Sensu agent
  hosts: localhost3
  roles:
    - benthomasson.hello_role3
    - sensu.sensu_go.agent
  vars:
    agent_config:
      backend-url: [ 'ws://upstream-backend:4321' ]