---
- name: Fail based on hostname
  strategy: free
  gather_facts: False
  hosts: all
  tasks:
  - name: "test fail task 1, succeeds, task that would fail is skipped"
    fail:
      msg: "Failed task 1"
    when: "'localhost1' in inventory_hostname"
  - name: "test fail task 2, failure ignored"
    fail:
      msg: "Failed task 2"
    when: "'localhost2' in inventory_hostname"
    retries: 3
    delay: 0
    register: result2
    until: result2 is not failed
    ignore_errors: yes
  - name: "test fail task 3"
    block:
      - name: "test fail task 3 fails inside rescue block"
        fail:
          msg: "Failed task 4"
        when: "'localhost3' in inventory_hostname"
    rescue:
      - debug:
          msg: "test fail task 3 rescue message"
  - name: "test fail task 4, unreachable host configured"
    shell: whoami
    when: "'localhost4' in inventory_hostname"
  - name: "test fail task 5, fails on localhost5"
    fail:
      msg: "Failed task 5"
    when: "'localhost5' in inventory_hostname"
  - name: "test fail task 6, failure ignored but fails on task 7"
    fail:
      msg: "Failed task 6"
    when: "'localhost6' in inventory_hostname"
  - name: "test fail task 7, fails on localhost6 and localhost7"
    fail:
      msg: "Failed task 7"
    when: "'localhost6' in inventory_hostname or 'localhost7' in inventory_hostname"
  - debug:
      msg: "Well done"
  